package ir.secure_msg.database;

import android.database.sqlite.SQLiteDatabase;

import ir.secure_msg.database.Contacts;
import ir.secure_msg.database.ContactsDao;
import ir.secure_msg.database.Message;
import ir.secure_msg.database.MessageDao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final ContactsDao contactsDao;
    private final MessageDao messageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsDaoConfig = daoConfigMap.get(ContactsDao.class).clone();
        contactsDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        contactsDao = new ContactsDao(contactsDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Contacts.class, contactsDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        contactsDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public ContactsDao getContactsDao() {
        return contactsDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
